#!/bin/csh
#Usage: build <version>
#Build MIDAS standard distribution

set version = $argv[1]
set dir = /tmp/midas-$version
set archive = midas-$version.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir

# checkout files
echo Checkout files...
cvs export -d $dir -D now midas

# create midas-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive midas-$version/

# remove temporary files
rm -Rf $dir

# generate .netrc
echo Transferring archive to pibeta via ftp
rm -f ~/.netrc
echo machine midas > ~/.netrc
echo login ftp >> ~/.netrc
echo password ritt@psi.ch >> ~/.netrc
echo macdef init >> ~/.netrc
echo cd pub/midas >> ~/.netrc
echo bin >> ~/.netrc
echo put $archive >> ~/.netrc
echo quit >> ~/.netrc
echo "" >> ~/.netrc
chmod 600 ~/.netrc

# ftp archive to pibeta
ftp midas
rm -f ~/.netrc

# remove archive
rm -f /tmp/$archive
