#!/bin/csh
#Usage: build <version>
#Build MIDAS standard distribution

set version = $argv[1]
set dir = /tmp/midas-$version
set archive = midas-$version.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir

# copy files
echo Copying files...
cp makefile $dir/
cp -r src/ $dir/src/
cp -r include/ $dir/include/
cp -r drivers/ $dir/drivers/
cp -r examples/ $dir/examples/
cp -r doc/     $dir/doc/
cp -r utils/   $dir/utils/
cp -r vxworks/ $dir/vxworks/
cp doc/readme.txt $dir/README
cp doc/install.txt $dir/INSTALL
cp doc/overview.txt $dir/OVERVIEW
rm -f $dir/examples/experiment/*.o
rm -f $dir/examples/experiment/frontend
rm -f $dir/examples/experiment/analyzer
rm -fr $dir/examples/experiment/bin
rm -fr $dir/examples/experiment/obj
rm -fr $dir/examples/ybosexpt/obj
rm -fr $dir/vxworks/obj
rm -rf $dir/ultrix
rm -rf $dir/osf1
rm -rf $dir/linux
rm -rf $dir/*~
rm -rf $dir/*/*~
rm -rf $dir/*/*/*~
rm -rf $dir/*/*/*/*~
rm -rf $dir/*.log
rm -rf $dir/*/*.log
rm -rf $dir/*/*/*.log
rm -rf $dir/*/*/*/*.log

rm -f $dir/doc/manual.doc
rm -f $dir/doc/manual_pictures.ppt

# create midas-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive midas-$version/

cd /midas
cp /tmp/$archive .

# remove temporary files
rm -Rf $dir
rm -f /tmp/$archive

# generate .netrc
echo Transferring archive to pibeta via ftp
rm -f ~/.netrc
echo machine pibeta > ~/.netrc
echo login ftp >> ~/.netrc
echo password ritt@psi.ch >> ~/.netrc
echo macdef init >> ~/.netrc
echo cd pub/midas >> ~/.netrc
echo bin >> ~/.netrc
echo put $archive >> ~/.netrc
echo quit >> ~/.netrc
echo "" >> ~/.netrc
chmod 600 ~/.netrc

# ftp archive to pibeta
ftp pibeta
rm -f ~/.netrc