#####################################################################
#
#  Name:         Makefile
#  Created by:   Suzannah Daviel, Konstantin Olchanski
#
#  Contents:     Makefile for MIDAS documentation
#
#  $Id$
#
#####################################################################
#
# Usage:
#        make              To compile the MIDAS documentation
#        make publish      To generate tarballs and copy them to the main MIDAS web site
#
#####################################################################

# Midas and Project version number
version = 2.3.0

all::	message

publish:
	message

ver:	
	echo "Frozen at version $(version)"


message:
	@echo "  " \  
	@echo " ========================================================================" \ 
	@echo " =  This version of the MIDAS Doc is frozen.                            = " \ 
	@echo " =                                                                      = " \   
	@echo " =  You can view this documentation at                                  = " \  
	@echo " =      http://ladd00.triumf.ca/~daqweb/doc/midas/doc/html/             = " \  
	@echo " =                                                                      = " \   
	@echo " = It is in the process of being replaced by a wiki at                  =   " \ 
	@echo " =      https://midas.triumf.ca/MidasWiki/index.php/Midas_documentation =" \ 
	@echo " ========================================================================" \  
	@echo "  " \          
# end
