#!/bin/csh
#Usage: build <version>
#Build MIDAS standard distribution

# go to midas root
cd ..

set version = $argv[1]
set dir = /tmp/midas-$version
set archive = midas-$version.tar.gz

# create temporary directory
rm -Rf $dir
mkdir $dir

# checkout files
echo Checkout files...
svn export --force file:///afs/psi.ch/project/meg/svn/midas/trunk $dir
svn export --force file:///afs/psi.ch/project/meg/svn/mxml/trunk /tmp/mxml

# create midas-x.xx.tar.gz file
echo Creating archive...
cd /tmp
tar -cvzf $archive midas-$version/ mxml/

# remove temporary files
rm -Rf $dir
rm -Rf /tmp/mxml

# copy to download area
cp /tmp/$archive ~/html/midas/download/tar/$archive
cd ~/midas
cp doc/CHANGELOG.TXT ~/html/midas/download/CHANGELOG

# remove archive
rm -f /tmp/$archive
