#!/usr/bin/perl
# above is magic first line to invoke perl
#
use warnings;
use strict;
# this script generates the alphabetical index docindex.dox
#
# to generate the contents, Organization.dox, run make_contents.pl following by doit.pl

our $debug =0;
our $idxd;

$|=1; # flush output buffers

require "./idx.pl";     # subroutines to make the alphabetical index are in idx.pl
require "./common_subs.pl";     # common subroutines between this file and contents.pl


print "make_index is starting\n";

# main dox Makefile does this : 
#
# 1. deletes Organization.dox, docindex.dox
# 2. makes contents list, Organization.dox
#       using make_contents.pl; doit.pl;
# 3. makes alphabetical index,  docindex.dox
#       using make_index.pl
# 4. deletes all temporary files generated by these scripts


# make alphabetical index
print "\n make_index.pl starting... making index ($idxd) \n";
idx(); 
fix_idx();
fix_idx2();
print "make_index:  docindex.dox is done\n";
print "To make the midas documentation, now make or make publish \n";
exit;
