#!/usr/bin/perl
# above is magic first line to invoke perl
#
use warnings;
use strict;
# this script generates the alphabetical index file "docindex.dox"
# Runs after make_contents.pl and doit.pl (which makes "Organization.dox")
# Calls index_add.pl to create the file index_add.txt ( additions to index i.e. see ->  ... )

our $indexfile="index_add.txt"; # extra items to be added to the index (input)
                                # index_add.txt is produced by index_add.pl
our $debug =0;
our $idxd;

$|=1; # flush output buffers

require "./idx.pl";     # subroutines to make the alphabetical index are in idx.pl
require "./common_subs.pl";     # common subroutines between this file and contents.pl


print "make_index is starting\n";

# main dox Makefile does this : 
#
# 
# 1. makes contents list, Organization.dox
#       using make_contents.pl; doit.pl;
# 2. makes alphabetical index,  docindex.dox
#       using make_index.pl
# 3. deletes all temporary files generated by these scripts


# make alphabetical index
print "\n make_index.pl starting... making index ($idxd) \n";
system ("index_add.pl");
unless (-e $indexfile) { die "Missing file $indexfile "; }
else { print "Successfully created $indexfile \n";} 
idx(); 
fix_idx();
fix_idx2();
print "make_index:  docindex.dox is done\n";
print "To make the midas documentation, now make or make publish \n";
exit;
