#!/bin/bash
#
# /etc/hotplug/usb/scs_250
#
# Sets up newly plugged in MSCB-USB submaster SCS-250 so that 
# all users can access it
#

if [ "${ACTION}" = "add" ] && [ -f "${DEVICE}" ]
then
    chmod 0666 "${DEVICE}"
fi
